name: Development

on:
  push:
    branches: [ dev ]

jobs:
  call-workflow:
    name: Production continuous integration
    uses: ./ci-cd.yml
    with:
      web-url: 'https://product-configurator-web.netlify.app'
      app-service-name: 'product-configurator-api'
      environment: Production
    secrets: inherit